###
# See here for config docs: https://github.com/mojombo/jekyll/wiki/Configuration
###

# Don't put these in the _site folder. 
exclude: [Gemfile, Gemfile.lock, ruten.ca.sublime-project, ruten.ca.sublime-workspace]

# Auto-regenerate site when files change
auto: true

# Don't publish posts with a future date. Allows scheduling, of sorts.
future: false

# Generates and index for related posts.
lsi: true

# Creates posts in a directory with an index.html
# permalink: pretty
permalink: /:year/:month/:day/:title

# Turn on pygments code highlighting
pygments: true

# Site Title for Open Graph Tags
title: Matt Ruten's Blog

# Site URL
url: http://ruten.ca

### Custom Config (non-Jekyll, for use in site templates etc.)
ruten:
  # Default Title: Probably only used on homepage
  default_title: "Matt Ruten - Web Developer in Toronto, Ontario"
  # Title text to append to post/etc. pages, i.e. "Post Title - Matt Ruten"
  title_append: " - Matt Ruten"
  # Social links
  twitter: http://twitter.com/mattruten
  feed: http://ruten.ca/atom.xml
  email_subscribe: "#" # TODO: Mailchimp RSS-to-Email or similar
